### ISSUE TITLE
NuGet install silently fails if targetting wrong framework

### ISSUE THREAD

**Issue by ryzngard** [GlitchEnzo/NuGetForUnity#189] opened 2018-10-04 19:13 UTC
## Description
Installing a package with only a differing API set than the editor targets fails silently. Example: NuGet package has netstandard2.0 libs only, and Unity Editor API set defaults to 4.x. The package restores without an error, but the DLLs in the package are not unpacked. 

- **NuGet Package:** Locally built, not available publicly
- **NuGetForUnity Version:** 0.0.17
- **Unity Version:** 2018.1 
- **Operating System:** Windows 10 1803

**Comment by jwittner** [comment] 2018-10-06 04:35
I'll try and replicate early next week.

**Comment by jwittner** [comment] 2018-10-08 20:53
If you configure Unity for .Net Standard 2.0 instead of 4.x do the right DLLs get installed?

I think you're experiencing expected behavior, but you're right we need an error message. The scan for acceptable frameworks starts here: https://github.com/GlitchEnzo/NuGetForUnity/blob/c688595871235a186dcf8629782243decf31e417/Assets/NuGet/Editor/NugetHelper.cs#L314

**Comment by jwittner** [comment] 2018-10-10 16:01
Looks like right now the code handles up to 462. You might try adding similar logic in the file above for 471 and see if it works. =)

**Comment by jwittner** [comment] 2018-12-20 21:55
I have work in progress on this now.

**Comment by anmelegov** [comment] 2019-02-04 10:35
It's a design bug. It's remove all DLLs after unpacking that are not pointed netframework. Even if the library targeted netstandard version that is implemented in netframework 4.6 (for example you cannot install library targeted netstandard 1.1)

**Comment by majaeger** [comment] 2019-10-30 17:21
The fix for #189 was trivial, so I went ahead and included it.

**Comment by jwittner** [comment] 2019-11-07 01:23
I believe this was resolved by #303

**Closed by jwittner** 2019-11-07 01:23 UTC
