### ISSUE TITLE
Ionic.Zip.ZipException: Cannot read that as a ZipFile

### ISSUE THREAD

**Issue by busiyg** [GlitchEnzo/NuGetForUnity#331] opened 2020-05-24 15:41 UTC
## Description

Ionic.Zip.ZipException: Cannot read that as a ZipFile ---> Ionic.Zip.BadReadException: Could not read block - no data!  (position 0x0002F3BF)
  at Ionic.Zip.SharedUtilities._ReadFourBytes (System.IO.Stream s, System.String message) [0x0002d] in <115b0c211e454f4b81d7eca9951b7383>:0 
  at Ionic.Zip.SharedUtilities.ReadInt (System.IO.Stream s) [0x00000] in <115b0c211e454f4b81d7eca9951b7383>:0 
  at Ionic.Zip.ZipEntry.HandleUnexpectedDataDescriptor (Ionic.Zip.ZipEntry entry) [0x00007] in <115b0c211e454f4b81d7eca9951b7383>:0 
  at Ionic.Zip.ZipEntry.ReadEntry (Ionic.Zip.ZipContainer zc, System.Boolean first) [0x00076] in <115b0c211e454f4b81d7eca9951b7383>:0 
  at Ionic.Zip.ZipFile.ReadIntoInstance_Orig (Ionic.Zip.ZipFile zf) [0x000b6] in <115b0c211e454f4b81d7eca9951b7383>:0 
  at Ionic.Zip.ZipFile.ReadIntoInstance (Ionic.Zip.ZipFile zf) [0x00144] in <115b0c211e454f4b81d7eca9951b7383>:0 
   --- End of inner exception stack trace ---
  at Ionic.Zip.ZipFile.ReadIntoInstance (Ionic.Zip.ZipFile zf) [0x0017c] in <115b0c211e454f4b81d7eca9951b7383>:0 
  at Ionic.Zip.ZipFile.Read (System.String fileName, System.IO.TextWriter statusMessageWriter, System.Text.Encoding encoding, System.EventHandler`1[TEventArgs] readProgress) [0x0004e] in <115b0c211e454f4b81d7eca9951b7383>:0 
  at Ionic.Zip.ZipFile.Read (System.String fileName) [0x00000] in <115b0c211e454f4b81d7eca9951b7383>:0 
  at NugetForUnity.NuspecFile.FromNupkgFile (System.String nupkgFilepath) [0x0000e] in <d5348c0adcb941678978d77f32d61a2a>:0 
  at NugetForUnity.NugetPackage.FromNupkgFile (System.String nupkgFilepath) [0x00000] in <d5348c0adcb941678978d77f32d61a2a>:0 
  at NugetForUnity.NugetHelper.GetCachedPackage (NugetForUnity.NugetPackageIdentifier packageId) [0x0004b] in <d5348c0adcb941678978d77f32d61a2a>:0 
  at NugetForUnity.NugetHelper.GetSpecificPackage (NugetForUnity.NugetPackageIdentifier packageId) [0x00010] in <d5348c0adcb941678978d77f32d61a2a>:0 
  at NugetForUnity.NugetHelper.InstallIdentifier (NugetForUnity.NugetPackageIdentifier package, System.Boolean refreshAssets) [0x00000] in <d5348c0adcb941678978d77f32d61a2a>:0 
  at NugetForUnity.NugetHelper.Restore () [0x000cc] in <d5348c0adcb941678978d77f32d61a2a>:0 
UnityEngine.Debug:LogErrorFormat(String, Object[])
NugetForUnity.NugetHelper:Restore()
NugetForUnity.NugetHelper:.cctor()
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes() (at D:/unity/Editor/Mono/EditorAssemblies.cs:168)

- **NuGet Package:** [null]
- **NuGetForUnity Version:** [2.0.0]
- **Unity Version:** [2018.4.14f]
- **Operating System:** [win10]

**Comment by jwittner** [comment] 2020-05-27 19:12
This looks like the nuget package it's trying to restore is corrupt. Can you try disabling the "Install from Cache" option in the NugetForUnity preferences pane inside the preferences window in Unity? If it reproduces still do you mind specifying what package is reproducing this?

**Comment by jwittner** [comment] 2021-01-28 03:20
Closing as there's no specific package information and I cannot reproduce.

**Closed by jwittner** 2021-01-28 03:20 UTC
