### ISSUE TITLE
Corrupted file while updating nuget package

### ISSUE THREAD

**Issue by thalbern** [GlitchEnzo/NuGetForUnity#296] opened 2019-10-09 13:18 UTC
## Description
I've updated from MRTK v 2.0.1 from the official nuget source to MRTK v 2.1.0 from our internal source. (Foundation and examples package). 
During the update I got this error message and unity crashed:

![image](https://user-images.githubusercontent.com/36998103/66484598-2dc38a00-ea9f-11e9-8640-572ed169eb05.png)

Note that I updated via the "Online" tab , not via "update" tab because there's no refresh button there to actually get my packages. 

(Possibly related: after this the new mrtk version was in the project but the example scenes were broken)

- **NuGet Package:** MRTK v 2.0.1 -> MRTK v 2.1.0
- **NuGetForUnity Version:** 1.2.4
- **Unity Version:** 2018.4.0f1
- **Operating System:** Windows 10

**Comment by JoC0de** [comment] 2023-08-12 19:49
Closing as it is a relay old bug an we can't reproduce.

**Closed by JoC0de** 2023-08-12 19:49 UTC
