### ISSUE TITLE
Can't install  System.Numerics.Vectors (without error message)

### ISSUE THREAD

**Issue by Merichbier** [GlitchEnzo/NuGetForUnity#379] opened 2021-03-16 17:15 UTC
## Description
Nuget find the package, but when clicking install, nothing happens (or fails silently as no error is shown in the console)

- **NuGet Package:**  System.Numerics.Vectors
- **NuGetForUnity Version:** NuGetForUnity Release 3.0.1
- **Unity Version:** Unity 2019.4.18f
- **Operating System:** Windows 10

**Comment by mikejurka** [comment] 2021-04-08 00:37
I'm also seeing this. If anyone else would like to chip in (or fix it), I placed a bounty up on https://www.bountysource.com/issues/97163690-can-t-install-system-numerics-vectors-without-error-message.

**Comment by jwittner** [comment] 2021-04-08 00:52
This was probably fixed already in #384, and it definitely fixed (just tested) without any errors (and avoiding any request) by #385. The outcome though is that no package is installed, because Unity already includes the System.Numerics.Vectors assemblies so NugetForUnity skips installation. Before #384 it was hitting a deprecated OData query. That's not the case with latest master in this repo now since it was merged. Once #385 goes through (waiting for others to help test/review before merging) it'll bypass the query entirely as we're skipping the request properly now for packages that Unity already includes.

If you're going through with the bounty @opexsdc deserves it as they made the PR that worked around the issue. =)

**Closed by jwittner** 2021-04-08 00:52 UTC

**Comment by mikejurka** [comment] 2021-04-08 01:01
@jwittner That's great, when is the next release coming out, or where can I find build instructions to build off master?

**Comment by jwittner** [comment] 2021-04-08 01:08
You can of course drop in the Source code directly, but if you want to replace with a package, you can make a new one by using the [build.ps1](https://github.com/GlitchEnzo/NuGetForUnity/blob/master/build.ps1) powershell script in the root directory. Can't believe we don't have documentation on how to use that script. Made #386 to track that.

You'll need Visual Studio and a couple of PowerShell modules installed for that script to work.

I'm hoping to release a new package on Monday as a colleague said they should be able to help review #385 before then and I want to get those changes in before stamping a new package. If anyone wanted to check out that PR and do some thorough testing I'd feel comfortable moving it in. =)

**Comment by mikejurka** [comment] 2021-04-08 01:27
I can confirm using https://github.com/jwittner/NuGetForUnity/tree/dev/versionRangeSupport fixed it (i also tried https://github.com/jwittner/NuGetForUnity/tree/master, d6971f2e4c92f299ec57108877310d6d595a3c24 and that had the same issue)
