### ISSUE TITLE
Allow switching between .net 3.x and 4.x

### ISSUE THREAD

**Issue by wldevries** [GlitchEnzo/NuGetForUnity#166] opened 2018-06-15 14:44 UTC
## Description
Nuget for Unity always installs the .net 3.x version of packages even when the project is set to .net 4.x. When you install a .net 4.x package it will result in an empty lib folder without any error message.

I would expect that Nuget for Unity would warns you when no dll is found and would extract the dlls for the proper .net framework version.

- **NuGet Package:**
Custom package that only contains .net 4.x dlls

- **NuGetForUnity Version:**
0.0.15

- **Unity Version:**
2018.1.0f2 64 bit

- **Operating System:**
Windows 10

**Comment by TylorF** [comment] 2018-06-15 23:54
I was making a bug ticket for the new AspNetCore SignalR packages not being properly extracted, but I think your ticket has just clued me into the cause. I did notice that I could just extract the .nupkg file and then they worked in my app as a workaround until this is fixed (easier than grabbing them off the site).

I'll put my report in this comment because they seem to be related, but might provide more info.

## Description
All the new Microsoft.AspNetCore.SignalR packages download the `.nupkg` file, but only create an empty lib folder.

- **NuGet Package:** 
  - Microsoft.AspNetCore.SignalR.1.0.0
  - Microsoft.AspNetCore.SignalR.Core.1.0.0
  - Microsoft.AspNetCore.SignalR.Common.1.0.0
  - Microsoft.AspNetCore.SignalR.Client.1.0.0
  - Microsoft.AspNetCore.SignalR.Client.Core.1.0.0
  - Microsoft.AspNetCore.SignalR.Protocols.Json.1.0.0
  - Microsoft.AspNetCore.SignalR.Protocols.MessagePack.1.0.0
- **NuGetForUnity Version:** 0.0.15
- **Unity Version:** 2018.1.3f1
- **Operating System:** Windows 10

**Comment by davidtruchon** [comment] 2018-07-24 14:02
I was about to open the same issue concerning the api compatibility level. My project is set to 4.6.1  with api compatibility to .Net Standard 2.0. I would expect nuget to fetch the .Net Standard version whenever possible and fallback on 4.6x libs but it creates an empty libs folder instead.

**Comment by jwittner** [comment] 2018-12-20 21:57
I am working on this now.

**Comment by Haaxor1689** [comment] 2019-05-13 16:21
Any update on this issue? I'm trying to use [MessagePack](https://github.com/neuecc/MessagePack-CSharp) as a dependency of my own nuget package but it doesn't download any dll files from MessagePack nuget.

**Comment by jwittner** [comment] 2019-05-13 16:37
Sorry, was working on this as a part of .net standard support when life took away my time to focus on it. A smaller change might be possible to resolve this specific issue so I'll look into that.

**Comment by jwittner** [comment] 2019-11-09 01:00
I believe this was fixed by #303

**Closed** 2019-11-09 01:00 UTC
