### ISSUE TITLE
TDLib Error in Unity

### ISSUE THREAD

**Issue by YauheniKhadanovich** [GlitchEnzo/NuGetForUnity#443] opened 2022-04-03 17:14 UTC
## Description
Please help me find a solution!
It is need to integrate Telegram into Unity on Android.
After installing TDLib, TDLib.Api, TDLibCore on Windows works fine. APK for Android is assembled without errors.
Error when running on Android (IL2CPP):
DllNotFoundException: Unable to load DLL 'tdjson': The specified module could not be found.

![image](https://user-images.githubusercontent.com/83750645/161439546-f8e1a56c-b7fa-49a7-9904-c3c49791157e.png)

- **NuGet Package:** TDLib,  TDLib.Api,  TDLibCore
- **NuGetForUnity Version:** 3.0.4
- **Unity Version:** 2020.3.25
- **Operating System:** Windows, Android

**Comment by Jeffy94** [comment] 2022-04-04 05:46
TDLib only depends on TDLib.Api
But at startup, TdJson.dll is also required!

**Comment by dayo05** [comment] 2022-06-04 16:05
I think this error has caused by this project not supportes native libraries yet. The PR exists but I don't know when will that marged.
#421

**Comment by JoC0de** [comment] 2024-10-29 20:27
Fixed by #631

**Closed by JoC0de** 2024-10-29 20:27 UTC
