### ISSUE TITLE
Installation (unnecessarily) slow?

### ISSUE THREAD

**Issue by daef** [GlitchEnzo/NuGetForUnity#199] opened 2018-11-02 22:06 UTC
Installing [Ipfs.Core](https://www.nuget.org/packages/Ipfs.Core/) takes forever. It seems like NuGetForUnity is extracting the same packages over and over. My best guess is that the [dependencies InstallIdentifier call](https://github.com/GlitchEnzo/NuGetForUnity/blob/928d3dca5b995b8d07dae58a9d24a352fbbcc1d0/Assets/NuGet/Editor/NugetHelper.cs#L1090) should pass a false to refreshPackages or something alike.

**Comment by JoC0de** [comment] 2023-08-12 20:55
Closing as the issue is very old and not reproducible.

**Closed by JoC0de** 2023-08-12 20:55 UTC
