### ISSUE TITLE
Json.Net and others install with too many dependencies

### ISSUE THREAD

**Issue by Merglasch** [GlitchEnzo/NuGetForUnity#216] opened 2018-12-14 11:14 UTC
## Description
Wanted to install Newtonsofts Json package. It installs what feels like the entire .Net Framework as additional dependencies. This creates many errors because of duplication and takes about 10 minutes just to install. It even installs stuff like System.Collections, Microsoft.CSharp and the .Net Standard Library  which I can't believe is correct :/

EDIT: Just Noticed that the issue "Installs Wrong Package Versions" seems to be about the same problem.

EDIT2: The problem also appears with SharpCompress 0.22 => not exclusive to Json.Net

EDIT3: Uninstalling the package dependency mess is also somewhat complicated :/

- **NuGet Package:** Json.Net 12.0.1
- **NuGetForUnity Version:** 1.0.2
- **Unity Version:** 2018.3
- **Operating System:** Win 10

**Comment by jwittner** [comment] 2018-12-14 19:12
Hey! I was able to reproduce this - it appears that installing from the cache is a part of the culprit too. When I disable that from the Preferences window I don't get the issue. Advise that as a work around for now until we sort this out.

**Comment by jwittner** [comment] 2018-12-14 20:21
Looks like update is still broken. I see the code now that is collapsing group dependencies into one list - we should be selecting the right set based on the target framework just as we do with the lib folder.

**Comment by jwittner** [comment] 2018-12-14 22:18
I'm working on a proper upgrade for the dependency groups, but you might try v0.0.17 if you need a version asap without this issue.

**Comment by Merglasch** [comment] 2018-12-17 11:35
thx, I have reset my branch and downgraded for now. I am looking forward to the upgrade.

**Comment by jwittner** [comment] 2018-12-20 21:54
Resolved by reverting change in #218 , now released as 1.0.3. Changes to support dependency groups, package target frameworks, and .net standard are in progress, but will slip into January. Wanted to revert this regression for everyone without waiting for that.

**Closed by jwittner** 2018-12-20 21:54 UTC
