### ISSUE TITLE
Settings in Manage NuGet Packages are not shared over multiple tabs

### ISSUE THREAD

**Issue by thalbern** [GlitchEnzo/NuGetForUnity#293] opened 2019-10-09 11:35 UTC
## Description
Ticking boxes like "Show all Versions" or "Show Prerelease" are not shared between tabs in Manage NuGet Packages. Eg if I tick the "Show Prerelease" in the Updates tab it won't be ticked in the Online tab.

- **NuGet Package:** Mrtk v2.1.0
- **NuGetForUnity Version:** 1.2.4
- **Unity Version:** 2018.4.0f1
- **Operating System:** Windows 10

**Comment by JoC0de** [comment] 2023-08-12 19:55
This is a feature not a bug 😄 Do you relay think the checkbox should be global?
I close it for now we can reopen it if multiple people suggest the change.

**Closed by JoC0de** 2023-08-12 19:55 UTC
