### ISSUE TITLE
Please support GitHub/GitLab nuget registry

### ISSUE THREAD

**Issue by LeoLeeCN** [GlitchEnzo/NuGetForUnity#462] opened 2022-08-02 09:43 UTC
Currently NugetForUnity couldn't fetch Nuget package from GitLab/GitHub.
GitHub/GitLab nuget registry is like: https://xxx.com/api/v4/projects/{project id}/packages/nuget/index.json

**Comment by deitry** [comment] 2022-12-24 17:15
I did a rough discovery that NuGet for Unity is tied to XML-based NuGet.org v2 API. For example:
https://github.com/GlitchEnzo/NuGetForUnity/blob/bbbc18b6583f73fa432a24fe6ba563b33a621e4d/Assets/NuGet/Editor/NugetPackageSource.cs#L359

If [v3 JSON API](https://learn.microsoft.com/en-us/nuget/api/overview) support will be implemented, then GitHub/GitLab will be supported automatically.

**Comment by deitry** [comment] 2022-12-24 17:17
Issue about v3 support: https://github.com/GlitchEnzo/NuGetForUnity/issues/229

**Comment by JoC0de** [comment] 2023-01-08 15:47
Duplicate of #229

**Closed by JoC0de** 2023-01-08 15:47 UTC
