### ISSUE TITLE
"BadReadException: Could not read block - no data!" exception for Microsoft.CognitiveServices.Speech

### ISSUE THREAD

**Issue by mattbenic** [GlitchEnzo/NuGetForUnity#327] opened 2020-03-31 14:04 UTC
## Description
An exception is thrown when trying to install the Microsoft.CognitiveServices.Speech package

- **NuGet Package:** Microsoft.CognitiveServices.Speech
- **NuGetForUnity Version:**  v2.0.0
- **Unity Version:** v2018.4.18f1
- **Operating System:** Windows 10

Stack trace:
```
BadReadException: Could not read block - no data!  (position 0x0162A849)
Ionic.Zip.SharedUtilities._ReadFourBytes (System.IO.Stream s, System.String message) (at <115b0c211e454f4b81d7eca9951b7383>:0)
Ionic.Zip.SharedUtilities.ReadInt (System.IO.Stream s) (at <115b0c211e454f4b81d7eca9951b7383>:0)
Ionic.Zip.ZipEntry.HandleUnexpectedDataDescriptor (Ionic.Zip.ZipEntry entry) (at <115b0c211e454f4b81d7eca9951b7383>:0)
Ionic.Zip.ZipEntry.ReadEntry (Ionic.Zip.ZipContainer zc, System.Boolean first) (at <115b0c211e454f4b81d7eca9951b7383>:0)
Ionic.Zip.ZipFile.ReadIntoInstance_Orig (Ionic.Zip.ZipFile zf) (at <115b0c211e454f4b81d7eca9951b7383>:0)
Ionic.Zip.ZipFile.ReadIntoInstance (Ionic.Zip.ZipFile zf) (at <115b0c211e454f4b81d7eca9951b7383>:0)
Rethrow as ZipException: Cannot read that as a ZipFile
Ionic.Zip.ZipFile.ReadIntoInstance (Ionic.Zip.ZipFile zf) (at <115b0c211e454f4b81d7eca9951b7383>:0)
Ionic.Zip.ZipFile.Read (System.String fileName, System.IO.TextWriter statusMessageWriter, System.Text.Encoding encoding, System.EventHandler`1[TEventArgs] readProgress) (at <115b0c211e454f4b81d7eca9951b7383>:0)
Ionic.Zip.ZipFile.Read (System.String fileName) (at <115b0c211e454f4b81d7eca9951b7383>:0)
NugetForUnity.NuspecFile.FromNupkgFile (System.String nupkgFilepath) (at <d5348c0adcb941678978d77f32d61a2a>:0)
NugetForUnity.NugetPackage.FromNupkgFile (System.String nupkgFilepath) (at <d5348c0adcb941678978d77f32d61a2a>:0)
NugetForUnity.NugetHelper.GetCachedPackage (NugetForUnity.NugetPackageIdentifier packageId) (at <d5348c0adcb941678978d77f32d61a2a>:0)
NugetForUnity.NugetHelper.GetSpecificPackage (NugetForUnity.NugetPackageIdentifier packageId) (at <d5348c0adcb941678978d77f32d61a2a>:0)
NugetForUnity.NugetHelper.InstallIdentifier (NugetForUnity.NugetPackageIdentifier package, System.Boolean refreshAssets) (at <d5348c0adcb941678978d77f32d61a2a>:0)
NugetForUnity.NugetWindow.DrawPackage (NugetForUnity.NugetPackage package, UnityEngine.GUIStyle packageStyle, UnityEngine.GUIStyle contrastStyle) (at <d5348c0adcb941678978d77f32d61a2a>:0)
NugetForUnity.NugetWindow.DrawPackages (System.Collections.Generic.List`1[T] packages) (at <d5348c0adcb941678978d77f32d61a2a>:0)
NugetForUnity.NugetWindow.DrawOnline () (at <d5348c0adcb941678978d77f32d61a2a>:0)
NugetForUnity.NugetWindow.OnGUI () (at <d5348c0adcb941678978d77f32d61a2a>:0)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:342)
UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:336)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition, UnityEngine.Rect viewRect) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:310)
UnityEditor.DockArea.DrawView (UnityEngine.Rect viewRect, UnityEngine.Rect dockAreaRect, System.Boolean customBorder, System.Boolean floatingWindow, System.Boolean isBottomTab) (at C:/buildslave/unity/build/Editor/Mono/GUI/DockArea.cs:361)
UnityEditor.DockArea.OldOnGUI () (at C:/buildslave/unity/build/Editor/Mono/GUI/DockArea.cs:320)
UnityEngine.Experimental.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout) (at C:/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:266)
UnityEngine.Experimental.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect) (at C:/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:438)
UnityEngine.Experimental.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e) (at C:/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:421)
UnityEngine.Experimental.UIElements.IMGUIContainer.HandleEvent (UnityEngine.Experimental.UIElements.EventBase evt) (at C:/buildslave/unity/build/Modules/UIElements/IMGUIContainer.cs:401)
UnityEngine.Experimental.UIElements.EventDispatcher.ProcessEvent (UnityEngine.Experimental.UIElements.EventBase evt, UnityEngine.Experimental.UIElements.IPanel panel) (at C:/buildslave/unity/build/Modules/UIElements/EventDispatcher.cs:511)
UnityEngine.Experimental.UIElements.EventDispatcher.Dispatch (UnityEngine.Experimental.UIElements.EventBase evt, UnityEngine.Experimental.UIElements.IPanel panel, UnityEngine.Experimental.UIElements.DispatchMode dispatchMode) (at C:/buildslave/unity/build/Modules/UIElements/EventDispatcher.cs:307)
UnityEngine.Experimental.UIElements.BaseVisualElementPanel.SendEvent (UnityEngine.Experimental.UIElements.EventBase e, UnityEngine.Experimental.UIElements.DispatchMode dispatchMode) (at C:/buildslave/unity/build/Modules/UIElements/Panel.cs:176)
UnityEngine.Experimental.UIElements.UIElementsUtility.DoDispatch (UnityEngine.Experimental.UIElements.BaseVisualElementPanel panel) (at C:/buildslave/unity/build/Modules/UIElements/UIElementsUtility.cs:245)
UnityEngine.Experimental.UIElements.UIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at C:/buildslave/unity/build/Modules/UIElements/UIElementsUtility.cs:68)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at C:/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:179)
```

**Comment by jwittner** [comment] 2020-06-05 23:47
Can you try to uncheck the 'Install From Cache' option in the N4U preferences inside Unity? Usually a corrupted download is the cause of this.

Please let me know!

**Comment by mattbenic** [comment] 2020-06-17 04:12
Thanks for the suggestion. I've since manually included the needed dlls. I'll give nuget a shot for this package again when I get a chance.

**Comment by snowxinyu** [comment] 2020-08-20 03:00
> Can you try to uncheck the 'Install From Cache' option in the N4U preferences inside Unity? Usually a corrupted download is the cause of this.
> 
> Please let me know!

How?Thanks.

**Comment by jwittner** [comment] 2021-01-28 03:22
I was able to install this without problem in Unity 2018.4.18f1 / N4U 3.0.0. Closing, but please reopen if you run into again.

**Closed by jwittner** 2021-01-28 03:22 UTC
