### ISSUE TITLE
NuGetForUnity ignores targetFramework

### ISSUE THREAD

**Issue by tbillington** [GlitchEnzo/NuGetForUnity#128] opened 2018-02-04 04:28 UTC
I'm trying to use NuGet to download [Grpc](https://grpc.io/docs/quickstart/csharp.html). In the example project all dependencies are specified with `targetFramework="net45"`, however when NuGetForUnity runs, the targetFramework is removed from the entries in `packages.config`.

The error I then get from Unity when trying to use the dependencies is `Unloading broken assembly Assets/Packages/Grpc.Core.1.8.0/lib/net45/Grpc.Core.dll, this assembly can cause crashes in the runtime` which could possibly be from not having the targetFramework?

[Grpc](https://grpc.io/docs/quickstart/csharp.html) requires `.NET Framework 4.5+` which shouldn't be an issue as I'm using Unity 2018.1 with the .NET 4.6 runtime.

**Comment by jwittner** [comment] 2018-02-04 18:32
NuGetForUnity, scans the lib folder target frameworks and selects the highest framework Unity can support in it's configuration. In your case it looks like the 'net45' folder was selected so that would be the target framework NuGetForUnity is trying to use for you.

Unfortunately I've seen this issue with broken assemblies on several net45 dlls and haven't been able to identify the problem, though it doesn't appear to be an issue with NuGetForUnity. Oddly I don't see this issue in 2017.1.1f1, which NuGetForUnity targets. I'm installing 2018.1.0b5 now and will check it out there later.

Closing as non-nuget bug.

**Closed by jwittner** 2018-02-04 18:32 UTC

**Comment by jwittner** [comment] 2018-02-04 18:43
Confirmed that I see the same issue in 2018.1.0b5 - recommend filing this with Unity to see what causes this issue.

**Comment by tbillington** [comment] 2018-02-05 08:31
@jwittner I can confirm that this issue isn't present in 2017.3.0f3. Do you know where I can report this issue to Unity, is there issue tracker the best place or the forum ?
