### ISSUE TITLE
When searching for `MsgPack` (or similar) whole Unity crashes. Other things are fine?

### ISSUE THREAD

**Issue by AgainPsychoX** [GlitchEnzo/NuGetForUnity#494] opened 2023-02-02 17:10 UTC
When searching for `MsgPack` (or similar) whole Unity crashes. Other things are fine?

-   **NuGet Package:** `MsgPack`
-   **NuGetForUnity Version:** 3.0.5
-   **Unity Version:** 2021.3.17f1 Personal <DX11>
-   **Operating System:** Windows 10.0.19045.2486

[Crash_2023-02-02_170626537.zip](https://github.com/GlitchEnzo/NuGetForUnity/files/10571473/Crash_2023-02-02_170626537.zip)

[msgpack is cursed.webm](https://user-images.githubusercontent.com/23557839/216394076-ed3d835d-4fd9-4a60-99b9-e344b2105146.webm)

**Comment by JoC0de** [comment] 2023-02-05 21:08
I tested it in the current master (that can be installed using UPM) but can't reproduce the error, eventually it only happens with Unity 2021.3.17f1 (I didn't tested it in this exact version).

**Comment by Dash83** [comment] 2023-02-16 11:13
I can confirm I'm seeing this bug as well when searching for `Google.Protobuf`. The editor shows an saying:

> System.IO.InvalidDataException: End of Central Directory record could not be found.

Is this perhaps related to this tool using the v2 of the nuget.org API, rather than v3 like the nuget cli tool does?

The environment in which reproduced is a Windows 11 machine (all patched up) running Unity 2021.3.17f1.

**Comment by JoC0de** [comment] 2023-02-19 21:47
Hi @Dash83 thanks for the bug report. There is a issue that the icons of some NuGet Packages are GIF format what is not supported by Unity buildin Texture2D. In the newest release 3.1.0 this is error is now ignored / catched.

**Comment by JoC0de** [comment] 2023-02-25 15:18
Fixed in 3.1.0

**Closed by JoC0de** 2023-02-25 15:18 UTC

**Comment by Dash83** [comment] 2023-02-28 16:22
Awesome, thanks!
