### ISSUE TITLE
Can't use a package if Newtonsoft.Json version is higher than 10

### ISSUE THREAD

**Issue by ghost** [GlitchEnzo/NuGetForUnity#279] opened 2019-09-11 18:24 UTC
## Description
Hello.

I'm using multiple packages:

- Google.Apis.1.41.1
- Google.Apis.Auth.1.41.1 (uses Newtonsoft.Json >= 10)
- Google.Apis.Core.1.41.1
- Google.Apis.YouTube.v3.1.41.1.1699
- LtGt.1.0.2
- Newtonsoft.Json.12.0.2
- Sprache.2.2.0
- YoutubeExplode.4.7.9 (uses Newtonsoft.Json >= 12)

Google package stops working as soon as Newtonsoft.Json version changes to anything above 10, it should work with anything above, but Unity yells it's not 10 and unloads the package.

Here's what it says:

`Error: Could not load signature of Google.Apis.Auth.GoogleJsonWebSignature+<>c:<GetGoogleCertsFromJson>b__16_0 due to: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. assembly:Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed type:<unknown type> member:(null) signature:<none>`

Is there anything I can do to fix this?
Are you still working on NuGetForUnity?

- **NuGet Package:** Google.Apis.Auth
- **NuGetForUnity Version:** 1.2.1
- **Unity Version:** 2019.2.4f1
- **Operating System:** macOS Mojave v10.14.6

**Comment by artnau42** [comment] 2019-09-13 08:16
Thank you for replying so soon.
> if you can discover the root cause and make a PR with a fix we'll gladly review and accept it
If only I could, then I wouldn't post the issue in first place and would just make a PR right away, but sadly I don't even know where to start, I'm not that kind of a programmer, mostly designer.
> This project is under active development
That's great. I just wanted to know if I can hope for somewhat close future solution of the issue or not. I guess for now I have to change the use of packages as I have no idea where to look at to even start thinking about a possible fix. If you have any guesses then maybe I could come up with something. Cheers!

**Comment by jwittner** [comment] 2019-09-14 00:05
Unfortunately I can't reproduce this on Windows 10 - I got the same set of packages above installed without issue. Also, looking at [Google.Apis.Auth](https://www.nuget.org/packages/Google.Apis.Auth/) - it doesn't appear to have a dependency on NewtonSoft.json.

Have you tried closing the project and reopening it? Unity can be pretty buggy with loading DLLs, especially if it's already loaded them. Often a simple restart will get it working again.

If the issue persists, do you mind adding more information about your setup?
* What platform are you targetting in Unity? I was aiming at PC, Mac, Linux Standalone.
* What scripting runtime/backend are you setup for? I was setup for .Net 4.6/Mono.

**Comment by artnau42** [comment] 2019-09-14 00:37
Huh, that's interesting. I guess it's macOS issue alone then _(as always)_.
Thank you for checking it for me, appreciate it.

> Have you tried closing the project and reopening it? Unity can be pretty buggy with loading DLLs, especially if it's already loaded them.

Yeah, I know about that behavior of Unity, so I've been restarting it after every experiment changes, but reloading DLLs didn't do anything.

Unity's targeting the same “PC, Mac & Linux Standalone” and scripting backend is Mono as well _(I only switch to IL2CPP for release builds, but that one didn't help with the issue as well anyway)_, API Compatibility is “.NET Standart 2.0” and changing it to “.NET 4.x” did nothing as well, so none of such changes helped in the end.

I think **Google.Apis.Auth** is certainly relies on **Newtonsoft.Json** _(in my case)_ since as soon as **Newtonsoft.Json** _v10.0.2_ appears in the project the error goes away, but reappears if I update **Newtonsoft.Json** to anything above _v10.0.2 (from 11.0.1 to 12.0.3)_. I think **Google.Apis** needs this package in general and being used inside of the **Auth** space, since all their systems are tied together in most cases I think that **Auth** wouldn't work alone separately anyway or vice versa.

I'll experiment a little more later and will let you know if there will be any new info on that issue.

**Comment by artnau42** [comment] 2019-09-14 00:58
I just wanted to add, that I saw many similar issues with **Newtonsoft.Json** all over the Internet while googling for _"Could not load file or assembly Newtonsoft.Json"_ error, but none of the suggested solutions there are applicable to Unity as in my case, because I can't control the project within the **Visual Studio** IDE.

**Comment by bmateus** [comment] 2020-01-22 19:35
I think I have a solution for this: 

1) Add the line:
`-appconfig:app.config`
to the csc.rsp file

2) Create a file called "app.config" in the root of your project (above assets folder)
with this in it:
`
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-12.0.0.0" newVersion="12.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
`

**Comment by Manurocker95** [comment] 2020-12-17 10:56
> I think I have a solution for this:
> 
> 1. Add the line:
>    `-appconfig:app.config`
>    to the csc.rsp file
> 2. Create a file called "app.config" in the root of your project (above assets folder)
>    with this in it:
> 
> ```
>     <?xml version="1.0" encoding="utf-8"?>
>     <configuration>
>       <runtime>
>         <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
>           <dependentAssembly>
>             <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
>             <bindingRedirect oldVersion="0.0.0.0-12.0.0.0" newVersion="12.0.0.0" />
>           </dependentAssembly>
>         </assemblyBinding>
>       </runtime>
>     </configuration>
> ```

I'm getting Error: Could not load signature of Google.Apis.Auth.GoogleJsonWebSignature+<>c:<GetGoogleCertsFromJson>b__16_0 due to: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. assembly:Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed type:<unknown type> member:(null) signature:<none>

Any clue?

**Comment by JoC0de** [comment] 2023-08-12 20:07
Closing as this is a old issue an Unity now has its own native Newtonsoft.Json version Json.Net.

**Closed by JoC0de** 2023-08-12 20:07 UTC
