### ISSUE TITLE
If project is in folder with '%20' in path then packages fail to install correctly

### ISSUE THREAD

**Issue by denravonska** [GlitchEnzo/NuGetForUnity#367] opened 2021-01-22 12:20 UTC
I'm trying to install CoordinateSharp for some GPS transformation calculations. It installs DLLs for several different .NET versions which seems to aggravate Unity:

> PrecompiledAssemblyException: Multiple precompiled assemblies with the same name CoordinateSharp.dll included or the current platform. Only one assembly with the same name is allowed per platform. Assembly paths: 
> Assets/Packages/CoordinateSharp.2.9.5.1/lib/netstandard1.4/CoordinateSharp.dll
> Assets/Packages/CoordinateSharp.2.9.5.1/lib/net40/CoordinateSharp.dll
> Assets/Packages/CoordinateSharp.2.9.5.1/lib/netstandard1.3/CoordinateSharp.dll
> Assets/Packages/CoordinateSharp.2.9.5.1/lib/netstandard2.0/CoordinateSharp.dll
> Assets/Packages/CoordinateSharp.2.9.5.1/lib/netstandard2.1/CoordinateSharp.dll

I can go to the DLLs in the Unity editor and disable the ones I don't need for my particular case, but I feel there must be a better way of doing this. I have seen this problems with two different packages, and seeing as I seem to be the only one with this problem it must be on my end.

- **NuGet Package:** CoordinateSharp
- **NuGetForUnity Version:** 3.0.0
- **Unity Version:** 2019.4.16f1
- **Operating System:** Linux

**Comment by jwittner** [comment] 2021-01-22 20:40
Hmmm, unforuntately I'm unable to reproduce this on Windows. I tried in Unity 2018.4 and 2019.4 targeting both .NET 4.x and .NET Standard 2.0 Api Compatibility Level settings. I suspect it's a Linux issue, which I'm not setup to test at the moment. If you could enable verbose logging in the NuGet for Unity preferences inside Unity and then try to install the package again that might give us some useful information on where the process is failing.

Please share the logs here after trying this. =)

![image](https://user-images.githubusercontent.com/12958442/105543676-ee7a7600-5cae-11eb-9316-9ca2c9e0afbd.png)

**Comment by denravonska** [comment] 2021-01-23 14:05
Here you go :)
[log.txt](https://github.com/GlitchEnzo/NuGetForUnity/files/5860306/log.txt)

**Comment by denravonska** [comment] 2021-01-23 14:10
I think I might have figured it out. The project in Azure had a space in the project name which was converted to `%20` when cloning. Removing that part seems to have fixed it.

**Comment by jwittner** [comment] 2021-01-25 23:10
Hmmm, seems like we should able to support paths that have been URL encoded if the OS supports it. Glad you found a work around!

**Comment by JoC0de** [comment] 2023-04-08 16:44
I am closing it as it should be fixed in current version. If someone else gets a similar issue pleas create a new issue.

**Closed by JoC0de** 2023-04-08 16:44 UTC
